#!/usr/bin/env python
'''
Execute the commands in a file
concurrently, n at a time
'''

import sys
from argparse import ArgumentParser
from hpcutils import concurrent_cmds

try:
    parser = ArgumentParser(description='Execute commands concurrently')
    parser.add_argument('-n', type=int, default=12,
                        help='Number of concurrent processes to execute. Default=12')
    parser.add_argument('file', type=file,
                        help='File containing commands, newline seperated.')
    args = parser.parse_args()
except IOError as e:
    print >> sys.stderr, e
    print args
    sys.exit(1)

commands = [line.strip() for line in args.file]
concurrent_cmds.run(commands, args.n)
