#!/usr/bin/env python
'''
Execute the commands in a file
concurrently, n at a time
'''

import sys
from argparse import ArgumentParser
from hpcutils import concurrent_cmds

try:
    parser = ArgumentParser(description='Execute commands concurrently')
    parser.add_argument('-n', type=int, default=12,
                        help='Number of concurrent processes to execute. Default=12')
    parser.add_argument('-s', type=float, default=1.0,
                        help='Time to sleep between checking if jobs have finished. Default = 1 s')
    parser.add_argument('file', type=file,
                        help='File containing commands, newline seperated.')
    args = parser.parse_args()
except IOError as e:
    print >> sys.stderr, e
    print args
    sys.exit(1)

lines = [line.strip() for line in args.file]
commands = [line for line in lines if not (line is '' or line.startswith('#'))]
num_concurrent = args.n
sleep_time = args.s
concurrent_cmds.run(commands, num_concurrent, sleep_time)
